baseURL = 'https://celso.io/'
languageCode = 'en-us'
title = 'Celso Martinho'
theme = "archie"
copyright = "Â© Celso Martinho"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
  pagerSize=10

[frontmatter]
  date=[':filename', ':default']
  section=['categories']

[permalinks]
	posts = '/:section/:year/:month/:day/:slugorcontentbasename/'

[params]
	mode="auto" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = """
ğŸ‘¶ From when Mosaic took over Gopher.  
ğŸ¢ VP of Engineering @ Cloudflare  
ğŸ•¹ï¸ Slightly addicted to retrocomputing"""
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[markup]
  [markup.goldmark]
    renderer.unsafe=true

# Social Tags

[[params.social]]
name = "Bluesky"
icon = "cloud"
url = "https://celso.bsky.social/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/celso"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/celsomartinho/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

# [[menu.main]]
# name = "Search"
# url = "#search"
# weight = 4

[module]
[[module.mounts]]
    source = 'assets'
    target = 'static/assets'
